### ISSUE TITLE
split admin and user swagger pages

### ISSUE THREAD

**Issue by jmmut** [EBIvariation/contig-alias#74]
it's been ok until now to have both apis togther, but if we plan to start asking users to test the contig alias, it would be clearer for them if we hide the admin endpoints.

**Comment by singaltanmay** [comment]
If the admin api still needs to be available we can all OAuth to it's Swagger section - https://www.baeldung.com/swagger-2-documentation-for-spring-rest-api#10-swagger-ui-with-an-oauth-secured-api
