### ISSUE TITLE
fix swagger serialization exceptions

### ISSUE THREAD

**Issue by jmmut** [EBIvariation/contig-alias#81]
This error shows up in the logs when running the service.

this probably comes from having a null int instead of an Integer for a default value in some endpoint.
```
2020-08-11 10:34:37.371  WARN 21295 --- [nio-8080-exec-2] i.s.m.p.AbstractSerializableParameter    : Illegal DefaultValue null for parameter type integer

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_211]
        ...
```

**Comment by singaltanmay** [comment]
This isn't an exception but is a log message generated by a library being used by springfox. I have tried a few common solutions but they haven't worked yet and need a lot of work to test fully (adding examples to all @ApiOperation).

https://github.com/springfox/springfox/issues/2528
https://github.com/springfox/springfox/issues/1100
https://www.dariawan.com/tutorials/rest/numberformatexception-for-input-string-in-swagger/

**Comment by singaltanmay** [comment]
Fixed by adding a dependecy https://mvnrepository.com/artifact/io.swagger/swagger-models
