### ISSUE TITLE
fix redirection to swagger page

### ISSUE THREAD

**Issue by jmmut** [EBIvariation/contig-alias#85]
if this is the root path, https://wwwdev.ebi.ac.uk/eva/webservices/contig-alias/ it should redirect to the swagger page, without having to manually type  https://wwwdev.ebi.ac.uk/eva/webservices/contig-alias/swagger-ui.html. 

Instead it shows a json that allows making a full paginated scan of the DB (http://wwwdev.ebi.ac.uk/eva/webservices/contig-alias/assemblyEntities). I didn't know about this feature but I guess it can be useful, so ideally this would still be available in another path. If both things are not possible, having the swagger in the root path is more important.

**Comment by singaltanmay** [comment]
I have been aware of this issue for a while now and have been trying multiple strings in the Swagger Interceptor but nothing seems to work.

**Comment by singaltanmay** [comment]
https://github.com/EBIvariation/contig-alias/blob/master/src/main/java/uk/ac/ebi/eva/contigalias/controller/swagger/SwaggerInterceptAdapter.java#L33

Checking for `req == null || req == "" || req.isEmpty()` should fix this is theory but it doesn't for some reason
